parser: babel-eslint

plugins:
- import
- react
- prettier
- import-order
- unicorn

extends:
- react-app
- airbnb
- prettier
- plugin:prettier/recommended
- plugin:import/errors
- plugin:import/warnings

env:
  node: true
  browser: true
  jest: true

parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true

settings:
  import/resolver:
    alias: true


rules:
  no-unused-expressions: off
  one-var: off
  react/sort-comp: off
  no-alert: off
  prettier/prettier: error
  default-case: off
  no-shadow: off
  linebreak-style: off
  eqeqeq: [error, smart]
  consistent-return: off
  prefer-const: error
  no-dupe-keys: error
  quotes: [error, single, { avoidEscape: false }]
  jsx-quotes: [error, prefer-single]
  no-restricted-globals: off
  no-return-assign: [error, except-parens]
  prefer-destructuring: off
  no-underscore-dangle: off
  no-use-before-define: [error, { functions: false, classes: true, variables: false }]
  no-prototype-builtins: off
  no-continue: off

  unicorn/import-index: error

  import/first: off
  import/prefer-default-export: off
  import/no-extraneous-dependencies: off
  import/no-unresolved: off
  import/order: off

  react/jsx-filename-extension: [error, { extensions: ['.js'] }]
  react/jsx-closing-bracket-location: off
  react/no-did-update-set-state: off

  react/forbid-prop-types: off
  react/prop-types: error
  react/require-default-props: error
  react/default-props-match-prop-types: error
  react/no-unused-prop-types: error
  react/no-unused-state: error
  react/prefer-stateless-function: error
  react/destructuring-assignment: off
  react/no-access-state-in-setstate: error
  react/jsx-wrap-multilines: error
  react/jsx-uses-vars: error
  react/jsx-uses-react: error
  react/no-did-mount-set-state: off


  class-methods-use-this: off
  jsx-a11y/anchor-has-content: off
  jsx-a11y/no-autofocus: off
  jsx-a11y/anchor-is-valid: off
  react/no-unescaped-entities: off
  react/no-array-index-key: off
  react/button-has-type: off
  no-param-reassign: off
  no-restricted-syntax: off
  camelcase: off
  react/jsx-no-bind: off
  react/jsx-pascal-case: off
  import/no-named-as-default: off
  jsx-a11y/heading-has-content: off
  global-require: off
  jsx-a11y/iframe-has-title: off
  jsx-a11y/label-has-for: off
  jsx-a11y/label-has-associated-control: off
  no-console: off
  no-plusplus: off
  jsx-a11y/no-noninteractive-element-interactions: off
  jsx-a11y/click-events-have-key-events: off
  no-nested-ternary: off
  jsx-a11y/no-static-element-interactions: off
  import/no-dynamic-require: off
  jsx-a11y/no-noninteractive-tabindex: off
  jsx-a11y/alt-text: off
