const FETCH_MOVIES = {
  REQUEST: '@@movies/FETCH_MOVIES_REQUEST',
  SUCCESS: '@@movies/FETCH_MOVIES_SUCCESS',
  ERROR: '@@movies/FETCH_MOVIES_ERROR',
};

const FETCH_MOVIE = {
  REQUEST: '@@movies/FETCH_MOVIE_REQUEST',
  SUCCESS: '@@movies/FETCH_MOVIE_SUCCESS',
  ERROR: '@@movies/FETCH_MOVIE_ERROR',
};

export { FETCH_MOVIES, FETCH_MOVIE };
